source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PBDataSourceKit_Example', :exclusive => true do
  pod "PBDataSourceKit", :path => "../"
end

target 'PBDataSourceKit_Tests', :exclusive => true do
  pod "PBDataSourceKit", :path => "../"

  
end
